version: '3'
services:
  web:
    image: kc12345/tcmg476:project
    ports:
      - "5000:5000"
    networks:
      - webnet
    links:
      - redis
  redis:
    image: "redis:alpine"
    networks:
      - webnet
networks:
  webnet:
